// <auto-generated />
using System;
using Cuzdan360Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuzdan360Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106183846_AddFinancialAdvicePersistence")]
    partial class AddFinancialAdvicePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.AssetType", b =>
                {
                    b.Property<int>("AssetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AssetTypeId");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            AssetTypeId = 1,
                            Code = "TRY",
                            Name = "Türk Lirası"
                        },
                        new
                        {
                            AssetTypeId = 2,
                            Code = "USD",
                            Name = "ABD Doları"
                        },
                        new
                        {
                            AssetTypeId = 3,
                            Code = "EUR",
                            Name = "Euro"
                        },
                        new
                        {
                            AssetTypeId = 4,
                            Code = "XAUTRY",
                            Name = "Gram Altın"
                        },
                        new
                        {
                            AssetTypeId = 5,
                            Code = "BTC",
                            Name = "Bitcoin"
                        },
                        new
                        {
                            AssetTypeId = 6,
                            Code = "STK",
                            Name = "Hisse Senedi"
                        },
                        new
                        {
                            AssetTypeId = 7,
                            Code = "FON",
                            Name = "Yatırım Fonu"
                        },
                        new
                        {
                            AssetTypeId = 8,
                            Code = "EMT",
                            Name = "Emtia"
                        },
                        new
                        {
                            AssetTypeId = 9,
                            Code = "BOND",
                            Name = "Tahvil/Bonolar"
                        });
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Maaş"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Ek Gelir"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Kira Geliri"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Diğer Gelirler"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Market & Gıda"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Faturalar"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Ulaşım"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Kira"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Restoran"
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Alışveriş"
                        },
                        new
                        {
                            CategoryId = 16,
                            Name = "Eğlence"
                        },
                        new
                        {
                            CategoryId = 17,
                            Name = "Sağlık"
                        },
                        new
                        {
                            CategoryId = 22,
                            Name = "Diğer Giderler"
                        });
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.FinancialAdvice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdviceText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContextSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdviceHistory");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastRunDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SourceId");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            SourceId = 1,
                            SourceName = "Nakit"
                        },
                        new
                        {
                            SourceId = 2,
                            SourceName = "Banka Hesabı"
                        },
                        new
                        {
                            SourceId = 3,
                            SourceName = "Kredi Kartı"
                        },
                        new
                        {
                            SourceId = 4,
                            SourceName = "Yatırım Hesabı"
                        });
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.UserAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssets");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.UserDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LenderName")
                        .HasColumnType("longtext");

                    b.Property<int>("RemainingInstallments")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDebts");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOtpEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastProfileUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MfaCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MfaCodeExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("longtext");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0,
                            Email = "admin@example.com",
                            IsEmailVerified = true,
                            IsOtpEnabled = false,
                            PasswordHash = "$2a$12$vDN5rfJgTGOrCvJ0354EueBJhTkQOt3cWqCnInML7TKC9qbDv/cYK",
                            Permission = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.FinancialAdvice", b =>
                {
                    b.HasOne("Cuzdan360Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.RecurringTransaction", b =>
                {
                    b.HasOne("Cuzdan360Backend.Models.Finance.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.Finance.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.Finance.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Category");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Transaction", b =>
                {
                    b.HasOne("Cuzdan360Backend.Models.Finance.AssetType", "AssetType")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.Finance.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.Finance.Source", "Source")
                        .WithMany("Transactions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Category");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.UserAsset", b =>
                {
                    b.HasOne("Cuzdan360Backend.Models.Finance.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.UserDebt", b =>
                {
                    b.HasOne("Cuzdan360Backend.Models.Finance.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuzdan360Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.AssetType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.Finance.Source", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cuzdan360Backend.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
